version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lending_protocol_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lending_user
      POSTGRES_PASSWORD: lending_password
      POSTGRES_DB: lending_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lending_user -d lending_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: lending_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lending.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data: